// Deterministic sample `data` payloads for every event in the catalog.
// Used by sendTestWebhook so the user can wire up a receiver without
// touching real records. Shapes mirror the event catalog in DESIGN.md.
//
// NOTE: Phase 03 emits real payloads from crm.functions.ts. If you add a
// new event in events.ts, you must update BOTH this file AND the matching
// emit site in crm.functions.ts so test deliveries match production shape.
import type { WebhookEvent } from "@/lib/webhooks/events";

const TEST_CONTACT = {
  id: "con_test_0001",
  full_name: "Test Contact",
  email: "test.contact@example.com",
  phone: "+1-555-0100",
  title: "VP of Testing",
  company_id: "com_test_0001",
  owner_id: "usr_test_0001",
  is_ideal_customer: 1,
  notes: "Sample contact generated by sendTestWebhook.",
  relationship_stage: "contact",
  stage_entered_at: "2026-05-19T17:42:11.039Z",
  archived_at: null,
  created_at: "2026-05-19T17:42:11.039Z",
  org_id: "org_test_0001",
} as const;

const TEST_DEAL = {
  id: "deal_test_0001",
  name: "Acme renewal",
  company_id: "com_test_0001",
  contact_id: "con_test_0001",
  stage: "won",
  value: 48000,
  probability: 100,
  expected_close: "2026-06-01",
  owner_id: "usr_test_0001",
  sort_order: 0,
  created_at: "2026-05-19T17:42:11.039Z",
  org_id: "org_test_0001",
} as const;

const TEST_LEAD = {
  id: "lead_test_0001",
  contact_id: "con_test_0001",
  source: "website",
  status: "new",
  score: 42,
  estimated_ltv: 12500,
  owner_id: "usr_test_0001",
  ai_reasoning: "Sample lead generated by sendTestWebhook.",
  created_at: "2026-05-19T17:42:11.039Z",
  org_id: "org_test_0001",
} as const;

const TEST_TICKET = {
  id: "tkt_test_0001",
  subject: "Test webhook delivery",
  description: "Sample ticket generated by sendTestWebhook.",
  status: "open",
  priority: "medium",
  contact_id: "con_test_0001",
  assigned_to: "usr_test_0001",
  created_by: "usr_test_0001",
  sla_due_at: "2026-05-20T17:42:11.039Z",
  resolved_at: null,
  resolution_note: null,
  last_escalated_at: null,
  created_at: "2026-05-19T17:42:11.039Z",
  org_id: "org_test_0001",
} as const;

const TEST_PURCHASE = {
  id: "pur_test_0001",
  contact_id: "con_test_0001",
  amount: 199,
  product: "Crema Sales Pro (monthly)",
  occurred_at: "2026-05-19T17:42:11.039Z",
  org_id: "org_test_0001",
} as const;

export function buildTestPayload(event: WebhookEvent): Record<string, unknown> {
  switch (event) {
    case "contact.created":
      return { contact: TEST_CONTACT };
    case "contact.archived":
      return {
        contact_id: TEST_CONTACT.id,
        archived_at: "2026-05-19T17:42:11.039Z",
      };
    case "contact.stage_changed":
      return {
        contact_id: TEST_CONTACT.id,
        from_stage: "lead",
        to_stage: "contact",
      };
    case "deal.created":
      return { deal: { ...TEST_DEAL, stage: "discovery", probability: 50 } };
    case "deal.stage_changed":
      return {
        deal_id: TEST_DEAL.id,
        from_stage: "proposal",
        to_stage: "closing",
      };
    case "deal.won":
      return { deal: TEST_DEAL, value: TEST_DEAL.value };
    case "deal.lost":
      return { deal: { ...TEST_DEAL, stage: "lost", probability: 0 } };
    case "lead.created":
      return { lead: TEST_LEAD };
    case "ticket.created":
      return { ticket: TEST_TICKET };
    case "ticket.status_changed":
      return {
        ticket_id: TEST_TICKET.id,
        from_status: "open",
        to_status: "pending",
      };
    case "ticket.resolved":
      return {
        ticket: {
          ...TEST_TICKET,
          status: "resolved",
          resolved_at: "2026-05-19T17:42:11.039Z",
          resolution_note: "Sample resolution.",
        },
      };
    case "purchase.created":
      return { purchase: TEST_PURCHASE, contact_id: TEST_PURCHASE.contact_id };
    case "relationship.status_changed":
      return {
        relationship_id: "rel_test_0001",
        from_status: "lead",
        to_status: "discovery",
      };
  }
}
