/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketingIndexRouteImport } from './routes/marketing.index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as TGuidRouteImport } from './routes/t.$guid'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as OnboardingCoachRouteImport } from './routes/onboarding.coach'
import { Route as MarketingDemoRouteImport } from './routes/marketing.demo'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InviteLinkTokenRouteImport } from './routes/invite-link.$token'
import { Route as ExtensionOnboardRouteImport } from './routes/extension.onboard'
import { Route as ApiDevSmokeEmailRouteImport } from './routes/api/dev-smoke-email'
import { Route as AuthenticatedTrafficRouteImport } from './routes/_authenticated/traffic'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRelationshipsRouteImport } from './routes/_authenticated/relationships'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedFunnelRouteImport } from './routes/_authenticated/funnel'
import { Route as AuthenticatedExtensionRouteImport } from './routes/_authenticated/extension'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedRelationshipsIndexRouteImport } from './routes/_authenticated/relationships.index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies.index'
import { Route as ApiV1TicketsRouteImport } from './routes/api/v1/tickets'
import { Route as ApiV1OpenapiRouteImport } from './routes/api/v1/openapi'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1DocsRouteImport } from './routes/api/v1/docs'
import { Route as ApiV1DealsRouteImport } from './routes/api/v1/deals'
import { Route as ApiV1ContactsRouteImport } from './routes/api/v1/contacts'
import { Route as ApiV1ActionsRouteImport } from './routes/api/v1/actions'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicPixelRouteImport } from './routes/api/public/pixel'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicIdentifyRouteImport } from './routes/api/public/identify'
import { Route as AuthenticatedRelationshipsIdRouteImport } from './routes/_authenticated/relationships.$id'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals.$id'
import { Route as AuthenticatedContactsIdRouteImport } from './routes/_authenticated/contacts.$id'
import { Route as AuthenticatedCompaniesIdRouteImport } from './routes/_authenticated/companies.$id'
import { Route as ApiV1ContactsIdRouteImport } from './routes/api/v1/contacts.$id'
import { Route as ApiV1CoachChatRouteImport } from './routes/api/v1/coach.chat'
import { Route as ApiPublicHooksSlaSweepRouteImport } from './routes/api/public/hooks/sla-sweep'
import { Route as ApiV1ContactsIdNotesRouteImport } from './routes/api/v1/contacts.$id.notes'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TGuidRoute = TGuidRouteImport.update({
  id: '/t/$guid',
  path: '/t/$guid',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCoachRoute = OnboardingCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => OnboardingRoute,
} as any)
const MarketingDemoRoute = MarketingDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => MarketingRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteLinkTokenRoute = InviteLinkTokenRouteImport.update({
  id: '/invite-link/$token',
  path: '/invite-link/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionOnboardRoute = ExtensionOnboardRouteImport.update({
  id: '/extension/onboard',
  path: '/extension/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevSmokeEmailRoute = ApiDevSmokeEmailRouteImport.update({
  id: '/api/dev-smoke-email',
  path: '/api/dev-smoke-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrafficRoute = AuthenticatedTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelationshipsRoute =
  AuthenticatedRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFunnelRoute = AuthenticatedFunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExtensionRoute = AuthenticatedExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelationshipsIndexRoute =
  AuthenticatedRelationshipsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRelationshipsRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const ApiV1TicketsRoute = ApiV1TicketsRouteImport.update({
  id: '/api/v1/tickets',
  path: '/api/v1/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiRoute = ApiV1OpenapiRouteImport.update({
  id: '/api/v1/openapi',
  path: '/api/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DocsRoute = ApiV1DocsRouteImport.update({
  id: '/api/v1/docs',
  path: '/api/v1/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DealsRoute = ApiV1DealsRouteImport.update({
  id: '/api/v1/deals',
  path: '/api/v1/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContactsRoute = ApiV1ContactsRouteImport.update({
  id: '/api/v1/contacts',
  path: '/api/v1/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ActionsRoute = ApiV1ActionsRouteImport.update({
  id: '/api/v1/actions',
  path: '/api/v1/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixelRoute = ApiPublicPixelRouteImport.update({
  id: '/api/public/pixel',
  path: '/api/public/pixel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIdentifyRoute = ApiPublicIdentifyRouteImport.update({
  id: '/api/public/identify',
  path: '/api/public/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelationshipsIdRoute =
  AuthenticatedRelationshipsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRelationshipsRoute,
  } as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDealsRoute,
} as any)
const AuthenticatedContactsIdRoute = AuthenticatedContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedContactsRoute,
} as any)
const AuthenticatedCompaniesIdRoute =
  AuthenticatedCompaniesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const ApiV1ContactsIdRoute = ApiV1ContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1ContactsRoute,
} as any)
const ApiV1CoachChatRoute = ApiV1CoachChatRouteImport.update({
  id: '/api/v1/coach/chat',
  path: '/api/v1/coach/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSlaSweepRoute = ApiPublicHooksSlaSweepRouteImport.update({
  id: '/api/public/hooks/sla-sweep',
  path: '/api/public/hooks/sla-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContactsIdNotesRoute = ApiV1ContactsIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ApiV1ContactsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/chat': typeof AuthenticatedChatRoute
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/developer': typeof AuthenticatedDeveloperRoute
  '/extension': typeof AuthenticatedExtensionRoute
  '/funnel': typeof AuthenticatedFunnelRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/relationships': typeof AuthenticatedRelationshipsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/traffic': typeof AuthenticatedTrafficRoute
  '/api/dev-smoke-email': typeof ApiDevSmokeEmailRoute
  '/extension/onboard': typeof ExtensionOnboardRoute
  '/invite-link/$token': typeof InviteLinkTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/demo': typeof MarketingDemoRoute
  '/onboarding/coach': typeof OnboardingCoachRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/t/$guid': typeof TGuidRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/marketing/': typeof MarketingIndexRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/relationships/$id': typeof AuthenticatedRelationshipsIdRoute
  '/api/public/identify': typeof ApiPublicIdentifyRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/pixel': typeof ApiPublicPixelRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/v1/actions': typeof ApiV1ActionsRoute
  '/api/v1/contacts': typeof ApiV1ContactsRouteWithChildren
  '/api/v1/deals': typeof ApiV1DealsRoute
  '/api/v1/docs': typeof ApiV1DocsRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/tickets': typeof ApiV1TicketsRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/relationships/': typeof AuthenticatedRelationshipsIndexRoute
  '/api/public/hooks/sla-sweep': typeof ApiPublicHooksSlaSweepRoute
  '/api/v1/coach/chat': typeof ApiV1CoachChatRoute
  '/api/v1/contacts/$id': typeof ApiV1ContactsIdRouteWithChildren
  '/api/v1/contacts/$id/notes': typeof ApiV1ContactsIdNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/chat': typeof AuthenticatedChatRoute
  '/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/deals': typeof AuthenticatedDealsRouteWithChildren
  '/developer': typeof AuthenticatedDeveloperRoute
  '/extension': typeof AuthenticatedExtensionRoute
  '/funnel': typeof AuthenticatedFunnelRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/traffic': typeof AuthenticatedTrafficRoute
  '/api/dev-smoke-email': typeof ApiDevSmokeEmailRoute
  '/extension/onboard': typeof ExtensionOnboardRoute
  '/invite-link/$token': typeof InviteLinkTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/demo': typeof MarketingDemoRoute
  '/onboarding/coach': typeof OnboardingCoachRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/t/$guid': typeof TGuidRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/marketing': typeof MarketingIndexRoute
  '/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/relationships/$id': typeof AuthenticatedRelationshipsIdRoute
  '/api/public/identify': typeof ApiPublicIdentifyRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/pixel': typeof ApiPublicPixelRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/v1/actions': typeof ApiV1ActionsRoute
  '/api/v1/contacts': typeof ApiV1ContactsRouteWithChildren
  '/api/v1/deals': typeof ApiV1DealsRoute
  '/api/v1/docs': typeof ApiV1DocsRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/tickets': typeof ApiV1TicketsRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/relationships': typeof AuthenticatedRelationshipsIndexRoute
  '/api/public/hooks/sla-sweep': typeof ApiPublicHooksSlaSweepRoute
  '/api/v1/coach/chat': typeof ApiV1CoachChatRoute
  '/api/v1/contacts/$id': typeof ApiV1ContactsIdRouteWithChildren
  '/api/v1/contacts/$id/notes': typeof ApiV1ContactsIdNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/contacts': typeof AuthenticatedContactsRouteWithChildren
  '/_authenticated/deals': typeof AuthenticatedDealsRouteWithChildren
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/extension': typeof AuthenticatedExtensionRoute
  '/_authenticated/funnel': typeof AuthenticatedFunnelRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/relationships': typeof AuthenticatedRelationshipsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/traffic': typeof AuthenticatedTrafficRoute
  '/api/dev-smoke-email': typeof ApiDevSmokeEmailRoute
  '/extension/onboard': typeof ExtensionOnboardRoute
  '/invite-link/$token': typeof InviteLinkTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/marketing/demo': typeof MarketingDemoRoute
  '/onboarding/coach': typeof OnboardingCoachRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/t/$guid': typeof TGuidRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/marketing/': typeof MarketingIndexRoute
  '/_authenticated/companies/$id': typeof AuthenticatedCompaniesIdRoute
  '/_authenticated/contacts/$id': typeof AuthenticatedContactsIdRoute
  '/_authenticated/deals/$id': typeof AuthenticatedDealsIdRoute
  '/_authenticated/relationships/$id': typeof AuthenticatedRelationshipsIdRoute
  '/api/public/identify': typeof ApiPublicIdentifyRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/pixel': typeof ApiPublicPixelRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/v1/actions': typeof ApiV1ActionsRoute
  '/api/v1/contacts': typeof ApiV1ContactsRouteWithChildren
  '/api/v1/deals': typeof ApiV1DealsRoute
  '/api/v1/docs': typeof ApiV1DocsRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/tickets': typeof ApiV1TicketsRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/relationships/': typeof AuthenticatedRelationshipsIndexRoute
  '/api/public/hooks/sla-sweep': typeof ApiPublicHooksSlaSweepRoute
  '/api/v1/coach/chat': typeof ApiV1CoachChatRoute
  '/api/v1/contacts/$id': typeof ApiV1ContactsIdRouteWithChildren
  '/api/v1/contacts/$id/notes': typeof ApiV1ContactsIdNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investors'
    | '/login'
    | '/marketing'
    | '/onboarding'
    | '/activity'
    | '/chat'
    | '/companies'
    | '/contacts'
    | '/deals'
    | '/developer'
    | '/extension'
    | '/funnel'
    | '/integrations'
    | '/relationships'
    | '/settings'
    | '/tickets'
    | '/today'
    | '/traffic'
    | '/api/dev-smoke-email'
    | '/extension/onboard'
    | '/invite-link/$token'
    | '/invite/$token'
    | '/marketing/demo'
    | '/onboarding/coach'
    | '/reset-password/$token'
    | '/t/$guid'
    | '/verify-email/$token'
    | '/marketing/'
    | '/companies/$id'
    | '/contacts/$id'
    | '/deals/$id'
    | '/relationships/$id'
    | '/api/public/identify'
    | '/api/public/ingest'
    | '/api/public/pixel'
    | '/api/public/track'
    | '/api/v1/actions'
    | '/api/v1/contacts'
    | '/api/v1/deals'
    | '/api/v1/docs'
    | '/api/v1/me'
    | '/api/v1/openapi'
    | '/api/v1/tickets'
    | '/companies/'
    | '/relationships/'
    | '/api/public/hooks/sla-sweep'
    | '/api/v1/coach/chat'
    | '/api/v1/contacts/$id'
    | '/api/v1/contacts/$id/notes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/investors'
    | '/login'
    | '/onboarding'
    | '/activity'
    | '/chat'
    | '/contacts'
    | '/deals'
    | '/developer'
    | '/extension'
    | '/funnel'
    | '/integrations'
    | '/settings'
    | '/tickets'
    | '/today'
    | '/traffic'
    | '/api/dev-smoke-email'
    | '/extension/onboard'
    | '/invite-link/$token'
    | '/invite/$token'
    | '/marketing/demo'
    | '/onboarding/coach'
    | '/reset-password/$token'
    | '/t/$guid'
    | '/verify-email/$token'
    | '/marketing'
    | '/companies/$id'
    | '/contacts/$id'
    | '/deals/$id'
    | '/relationships/$id'
    | '/api/public/identify'
    | '/api/public/ingest'
    | '/api/public/pixel'
    | '/api/public/track'
    | '/api/v1/actions'
    | '/api/v1/contacts'
    | '/api/v1/deals'
    | '/api/v1/docs'
    | '/api/v1/me'
    | '/api/v1/openapi'
    | '/api/v1/tickets'
    | '/companies'
    | '/relationships'
    | '/api/public/hooks/sla-sweep'
    | '/api/v1/coach/chat'
    | '/api/v1/contacts/$id'
    | '/api/v1/contacts/$id/notes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/investors'
    | '/login'
    | '/marketing'
    | '/onboarding'
    | '/_authenticated/activity'
    | '/_authenticated/chat'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/deals'
    | '/_authenticated/developer'
    | '/_authenticated/extension'
    | '/_authenticated/funnel'
    | '/_authenticated/integrations'
    | '/_authenticated/relationships'
    | '/_authenticated/settings'
    | '/_authenticated/tickets'
    | '/_authenticated/today'
    | '/_authenticated/traffic'
    | '/api/dev-smoke-email'
    | '/extension/onboard'
    | '/invite-link/$token'
    | '/invite/$token'
    | '/marketing/demo'
    | '/onboarding/coach'
    | '/reset-password/$token'
    | '/t/$guid'
    | '/verify-email/$token'
    | '/marketing/'
    | '/_authenticated/companies/$id'
    | '/_authenticated/contacts/$id'
    | '/_authenticated/deals/$id'
    | '/_authenticated/relationships/$id'
    | '/api/public/identify'
    | '/api/public/ingest'
    | '/api/public/pixel'
    | '/api/public/track'
    | '/api/v1/actions'
    | '/api/v1/contacts'
    | '/api/v1/deals'
    | '/api/v1/docs'
    | '/api/v1/me'
    | '/api/v1/openapi'
    | '/api/v1/tickets'
    | '/_authenticated/companies/'
    | '/_authenticated/relationships/'
    | '/api/public/hooks/sla-sweep'
    | '/api/v1/coach/chat'
    | '/api/v1/contacts/$id'
    | '/api/v1/contacts/$id/notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InvestorsRoute: typeof InvestorsRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ApiDevSmokeEmailRoute: typeof ApiDevSmokeEmailRoute
  ExtensionOnboardRoute: typeof ExtensionOnboardRoute
  InviteLinkTokenRoute: typeof InviteLinkTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  TGuidRoute: typeof TGuidRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
  ApiPublicIdentifyRoute: typeof ApiPublicIdentifyRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicPixelRoute: typeof ApiPublicPixelRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiV1ActionsRoute: typeof ApiV1ActionsRoute
  ApiV1ContactsRoute: typeof ApiV1ContactsRouteWithChildren
  ApiV1DealsRoute: typeof ApiV1DealsRoute
  ApiV1DocsRoute: typeof ApiV1DocsRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1OpenapiRoute: typeof ApiV1OpenapiRoute
  ApiV1TicketsRoute: typeof ApiV1TicketsRoute
  ApiPublicHooksSlaSweepRoute: typeof ApiPublicHooksSlaSweepRoute
  ApiV1CoachChatRoute: typeof ApiV1CoachChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/': {
      id: '/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$guid': {
      id: '/t/$guid'
      path: '/t/$guid'
      fullPath: '/t/$guid'
      preLoaderRoute: typeof TGuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/coach': {
      id: '/onboarding/coach'
      path: '/coach'
      fullPath: '/onboarding/coach'
      preLoaderRoute: typeof OnboardingCoachRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/marketing/demo': {
      id: '/marketing/demo'
      path: '/demo'
      fullPath: '/marketing/demo'
      preLoaderRoute: typeof MarketingDemoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-link/$token': {
      id: '/invite-link/$token'
      path: '/invite-link/$token'
      fullPath: '/invite-link/$token'
      preLoaderRoute: typeof InviteLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/onboard': {
      id: '/extension/onboard'
      path: '/extension/onboard'
      fullPath: '/extension/onboard'
      preLoaderRoute: typeof ExtensionOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-smoke-email': {
      id: '/api/dev-smoke-email'
      path: '/api/dev-smoke-email'
      fullPath: '/api/dev-smoke-email'
      preLoaderRoute: typeof ApiDevSmokeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/traffic': {
      id: '/_authenticated/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof AuthenticatedTrafficRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relationships': {
      id: '/_authenticated/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof AuthenticatedRelationshipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funnel': {
      id: '/_authenticated/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof AuthenticatedFunnelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extension': {
      id: '/_authenticated/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof AuthenticatedExtensionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relationships/': {
      id: '/_authenticated/relationships/'
      path: '/'
      fullPath: '/relationships/'
      preLoaderRoute: typeof AuthenticatedRelationshipsIndexRouteImport
      parentRoute: typeof AuthenticatedRelationshipsRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/api/v1/tickets': {
      id: '/api/v1/tickets'
      path: '/api/v1/tickets'
      fullPath: '/api/v1/tickets'
      preLoaderRoute: typeof ApiV1TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi': {
      id: '/api/v1/openapi'
      path: '/api/v1/openapi'
      fullPath: '/api/v1/openapi'
      preLoaderRoute: typeof ApiV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/docs': {
      id: '/api/v1/docs'
      path: '/api/v1/docs'
      fullPath: '/api/v1/docs'
      preLoaderRoute: typeof ApiV1DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/deals': {
      id: '/api/v1/deals'
      path: '/api/v1/deals'
      fullPath: '/api/v1/deals'
      preLoaderRoute: typeof ApiV1DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contacts': {
      id: '/api/v1/contacts'
      path: '/api/v1/contacts'
      fullPath: '/api/v1/contacts'
      preLoaderRoute: typeof ApiV1ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/actions': {
      id: '/api/v1/actions'
      path: '/api/v1/actions'
      fullPath: '/api/v1/actions'
      preLoaderRoute: typeof ApiV1ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pixel': {
      id: '/api/public/pixel'
      path: '/api/public/pixel'
      fullPath: '/api/public/pixel'
      preLoaderRoute: typeof ApiPublicPixelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/identify': {
      id: '/api/public/identify'
      path: '/api/public/identify'
      fullPath: '/api/public/identify'
      preLoaderRoute: typeof ApiPublicIdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relationships/$id': {
      id: '/_authenticated/relationships/$id'
      path: '/$id'
      fullPath: '/relationships/$id'
      preLoaderRoute: typeof AuthenticatedRelationshipsIdRouteImport
      parentRoute: typeof AuthenticatedRelationshipsRoute
    }
    '/_authenticated/deals/$id': {
      id: '/_authenticated/deals/$id'
      path: '/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedDealsRoute
    }
    '/_authenticated/contacts/$id': {
      id: '/_authenticated/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AuthenticatedContactsIdRouteImport
      parentRoute: typeof AuthenticatedContactsRoute
    }
    '/_authenticated/companies/$id': {
      id: '/_authenticated/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof AuthenticatedCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/api/v1/contacts/$id': {
      id: '/api/v1/contacts/$id'
      path: '/$id'
      fullPath: '/api/v1/contacts/$id'
      preLoaderRoute: typeof ApiV1ContactsIdRouteImport
      parentRoute: typeof ApiV1ContactsRoute
    }
    '/api/v1/coach/chat': {
      id: '/api/v1/coach/chat'
      path: '/api/v1/coach/chat'
      fullPath: '/api/v1/coach/chat'
      preLoaderRoute: typeof ApiV1CoachChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sla-sweep': {
      id: '/api/public/hooks/sla-sweep'
      path: '/api/public/hooks/sla-sweep'
      fullPath: '/api/public/hooks/sla-sweep'
      preLoaderRoute: typeof ApiPublicHooksSlaSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contacts/$id/notes': {
      id: '/api/v1/contacts/$id/notes'
      path: '/notes'
      fullPath: '/api/v1/contacts/$id/notes'
      preLoaderRoute: typeof ApiV1ContactsIdNotesRouteImport
      parentRoute: typeof ApiV1ContactsIdRoute
    }
  }
}

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesIdRoute: typeof AuthenticatedCompaniesIdRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesIdRoute: AuthenticatedCompaniesIdRoute,
    AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedContactsRouteChildren {
  AuthenticatedContactsIdRoute: typeof AuthenticatedContactsIdRoute
}

const AuthenticatedContactsRouteChildren: AuthenticatedContactsRouteChildren = {
  AuthenticatedContactsIdRoute: AuthenticatedContactsIdRoute,
}

const AuthenticatedContactsRouteWithChildren =
  AuthenticatedContactsRoute._addFileChildren(
    AuthenticatedContactsRouteChildren,
  )

interface AuthenticatedDealsRouteChildren {
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
}

const AuthenticatedDealsRouteChildren: AuthenticatedDealsRouteChildren = {
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
}

const AuthenticatedDealsRouteWithChildren =
  AuthenticatedDealsRoute._addFileChildren(AuthenticatedDealsRouteChildren)

interface AuthenticatedRelationshipsRouteChildren {
  AuthenticatedRelationshipsIdRoute: typeof AuthenticatedRelationshipsIdRoute
  AuthenticatedRelationshipsIndexRoute: typeof AuthenticatedRelationshipsIndexRoute
}

const AuthenticatedRelationshipsRouteChildren: AuthenticatedRelationshipsRouteChildren =
  {
    AuthenticatedRelationshipsIdRoute: AuthenticatedRelationshipsIdRoute,
    AuthenticatedRelationshipsIndexRoute: AuthenticatedRelationshipsIndexRoute,
  }

const AuthenticatedRelationshipsRouteWithChildren =
  AuthenticatedRelationshipsRoute._addFileChildren(
    AuthenticatedRelationshipsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRouteWithChildren
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRouteWithChildren
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedExtensionRoute: typeof AuthenticatedExtensionRoute
  AuthenticatedFunnelRoute: typeof AuthenticatedFunnelRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedRelationshipsRoute: typeof AuthenticatedRelationshipsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTrafficRoute: typeof AuthenticatedTrafficRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedContactsRoute: AuthenticatedContactsRouteWithChildren,
  AuthenticatedDealsRoute: AuthenticatedDealsRouteWithChildren,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedExtensionRoute: AuthenticatedExtensionRoute,
  AuthenticatedFunnelRoute: AuthenticatedFunnelRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedRelationshipsRoute: AuthenticatedRelationshipsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTrafficRoute: AuthenticatedTrafficRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MarketingRouteChildren {
  MarketingDemoRoute: typeof MarketingDemoRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingDemoRoute: MarketingDemoRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingCoachRoute: typeof OnboardingCoachRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCoachRoute: OnboardingCoachRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface ApiV1ContactsIdRouteChildren {
  ApiV1ContactsIdNotesRoute: typeof ApiV1ContactsIdNotesRoute
}

const ApiV1ContactsIdRouteChildren: ApiV1ContactsIdRouteChildren = {
  ApiV1ContactsIdNotesRoute: ApiV1ContactsIdNotesRoute,
}

const ApiV1ContactsIdRouteWithChildren = ApiV1ContactsIdRoute._addFileChildren(
  ApiV1ContactsIdRouteChildren,
)

interface ApiV1ContactsRouteChildren {
  ApiV1ContactsIdRoute: typeof ApiV1ContactsIdRouteWithChildren
}

const ApiV1ContactsRouteChildren: ApiV1ContactsRouteChildren = {
  ApiV1ContactsIdRoute: ApiV1ContactsIdRouteWithChildren,
}

const ApiV1ContactsRouteWithChildren = ApiV1ContactsRoute._addFileChildren(
  ApiV1ContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InvestorsRoute: InvestorsRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  ApiDevSmokeEmailRoute: ApiDevSmokeEmailRoute,
  ExtensionOnboardRoute: ExtensionOnboardRoute,
  InviteLinkTokenRoute: InviteLinkTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  TGuidRoute: TGuidRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
  ApiPublicIdentifyRoute: ApiPublicIdentifyRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicPixelRoute: ApiPublicPixelRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiV1ActionsRoute: ApiV1ActionsRoute,
  ApiV1ContactsRoute: ApiV1ContactsRouteWithChildren,
  ApiV1DealsRoute: ApiV1DealsRoute,
  ApiV1DocsRoute: ApiV1DocsRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1OpenapiRoute: ApiV1OpenapiRoute,
  ApiV1TicketsRoute: ApiV1TicketsRoute,
  ApiPublicHooksSlaSweepRoute: ApiPublicHooksSlaSweepRoute,
  ApiV1CoachChatRoute: ApiV1CoachChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
